'use client';

import { Canvas, useFrame, useThree } from '@react-three/fiber';
import { ContactShadows, Environment, Float, RoundedBox, Sparkles } from '@react-three/drei';
import { CuboidCollider, Physics, RigidBody, type RapierRigidBody } from '@react-three/rapier';
import { Suspense, useEffect, useMemo, useRef, useState } from 'react';
import * as THREE from 'three';
import { scenes } from './data';
import { palette as p } from './palette';
import { useGameStore } from './store';
import type { SceneDefinition, SceneId, StudySpot, Vec3 } from './types';
import { clampDuration, distanceXZ, formatTime, remainingMs, yawForMovement } from './utils';

const Box=({position=[0,0,0],scale=[1,1,1],color=p.warmWood,radius=.08,children,rotation=[0,0,0]}:{position?:Vec3;scale?:Vec3;color?:string;radius?:number;children?:React.ReactNode;rotation?:Vec3})=><RoundedBox position={position} scale={scale} radius={radius} smoothness={2} rotation={rotation}><meshToonMaterial color={color}/>{children}</RoundedBox>;
const Cyl=({position=[0,0,0],scale=[1,1,1],color=p.warmWood,rotation=[0,0,0]}:{position?:Vec3;scale?:Vec3;color?:string;rotation?:Vec3})=><mesh position={position} scale={scale} rotation={rotation}><cylinderGeometry args={[.5,.55,1,10]}/><meshToonMaterial color={color}/></mesh>;

function Character({variant=0,position=[0,0,0],rotation=0,moving=false,seated=false,activity='idle',scale=1}:{variant?:number;position?:Vec3;rotation?:number;moving?:boolean;seated?:boolean;activity?:string;scale?:number}){
  const root=useRef<THREE.Group>(null), leftArm=useRef<THREE.Group>(null),rightArm=useRef<THREE.Group>(null),leftLeg=useRef<THREE.Group>(null),rightLeg=useRef<THREE.Group>(null),head=useRef<THREE.Group>(null);
  const skins=['#c98962','#efb18b','#85513c'],hairs=['#30221e','#bd5739','#251d2b'],shirts=['#e57734','#4e8c9e','#e2b744'],bottoms=['#39749c','#5b718c','#5e557d'];
  useFrame(({clock})=>{const t=clock.elapsedTime;if(!root.current)return;root.current.position.y=position[1]+(moving?Math.abs(Math.sin(t*8))*.055:Math.sin(t*2)*.012);if(head.current)head.current.rotation.y=Math.sin(t*.7)*.04;const swing=moving?Math.sin(t*8)*.55:activity==='typing'?Math.sin(t*5)*.08:0;if(leftArm.current){leftArm.current.rotation.x=seated?-1.1:swing;leftArm.current.rotation.z=activity==='wave'?-.6+Math.sin(t*7)*.35:0}if(rightArm.current)rightArm.current.rotation.x=seated?-1.1:-swing;if(leftLeg.current)leftLeg.current.rotation.x=seated?-1.42:-swing;if(rightLeg.current)rightLeg.current.rotation.x=seated?-1.42:swing;});
  return <group ref={root} position={position} rotation={[0,rotation,0]} scale={scale}>
    <group ref={head} position={[0,1.46,0]}>
      <mesh scale={[.72,.67,.67]} castShadow><sphereGeometry args={[.62,20,16]}/><meshToonMaterial color={skins[variant]}/></mesh>
      <mesh position={[0,.22,-.12]} scale={[.76,.42,.68]} castShadow><sphereGeometry args={[.62,18,12]}/><meshToonMaterial color={hairs[variant]}/></mesh>
      {variant===0&&[-.36,-.12,.13,.37].map((x,i)=><mesh key={i} position={[x,.35,.22]} rotation={[0,0,(x)*.6]} scale={[.23,.34,.2]}><sphereGeometry args={[.5,12,8]}/><meshToonMaterial color={hairs[variant]}/></mesh>)}
      {variant===1&&<><mesh position={[-.57,.05,-.05]} scale={[.3,.55,.3]}><sphereGeometry args={[.5,12,8]}/><meshToonMaterial color={hairs[variant]}/></mesh><mesh position={[.57,.02,-.05]} scale={[.3,.55,.3]}><sphereGeometry args={[.5,12,8]}/><meshToonMaterial color={hairs[variant]}/></mesh></>}
      {variant===2&&[[-.42,.28,0],[-.15,.42,-.05],[.18,.43,-.05],[.45,.25,0],[-.55,.02,-.05],[.56,.02,-.05]].map((v,i)=><mesh key={i} position={v as Vec3} scale={.37}><sphereGeometry args={[.5,12,8]}/><meshToonMaterial color={hairs[variant]}/></mesh>)}
      {[-.24,.24].map((x,i)=><group key={x}><mesh position={[x,.02,.57]} scale={[.14,.18,.06]}><sphereGeometry args={[.5,12,8]}/><meshToonMaterial color="#fff8e9"/></mesh><mesh position={[x+(i?-.02:.02),.01,.61]} scale={[.065,.09,.03]}><sphereGeometry args={[.5,10,8]}/><meshToonMaterial color="#302726"/></mesh></group>)}
      <mesh position={[0,-.2,.6]} rotation={[Math.PI/2,0,0]}><torusGeometry args={[.1,.018,6,12,Math.PI]}/><meshToonMaterial color="#8a3f38"/></mesh>
      <mesh position={[-.32,-.17,.57]} scale={[.09,.04,.02]}><sphereGeometry args={[.5,8,6]}/><meshToonMaterial color="#e98678"/></mesh><mesh position={[.32,-.17,.57]} scale={[.09,.04,.02]}><sphereGeometry args={[.5,8,6]}/><meshToonMaterial color="#e98678"/></mesh>
    </group>
    <RoundedBox position={[0,.78,0]} scale={[.68,.62,.42]} radius={.18} smoothness={3} castShadow><meshToonMaterial color={shirts[variant]}/></RoundedBox>
    {variant===0&&[.56,.78,.99].map(y=><Box key={y} position={[0,y,.225]} scale={[.62,.055,.02]} color={p.warmCream} radius={.01}/>)}
    {variant===1&&<><Box position={[0,.73,.23]} scale={[.42,.5,.03]} color="#476b80"/><Box position={[-.18,1.03,.24]} scale={[.07,.36,.03]} color="#476b80"/><Box position={[.18,1.03,.24]} scale={[.07,.36,.03]} color="#476b80"/></>}
    <group ref={leftArm} position={[-.42,.95,0]}><Cyl position={[0,-.25,0]} scale={[.22,.55,.22]} color={shirts[variant]}/><mesh position={[0,-.56,0]} scale={.16}><sphereGeometry args={[.5,10,8]}/><meshToonMaterial color={skins[variant]}/></mesh></group>
    <group ref={rightArm} position={seated?[.42,.95,0]:[.42,.95,0]}><Cyl position={[0,-.25,0]} scale={[.22,.55,.22]} color={shirts[variant]}/><mesh position={[0,-.56,0]} scale={.16}><sphereGeometry args={[.5,10,8]}/><meshToonMaterial color={skins[variant]}/></mesh></group>
    <group ref={leftLeg} position={[-.19,.5,0]}><Cyl position={[0,-.24,0]} scale={[.25,.48,.25]} color={bottoms[variant]}/><Box position={[0,-.49,.08]} scale={[.34,.18,.5]} color="#fff7e7"/></group>
    <group ref={rightLeg} position={seated?[.19,.5,0]:[.19,.5,0]}><Cyl position={[0,-.24,0]} scale={[.25,.48,.25]} color={bottoms[variant]}/><Box position={[0,-.49,.08]} scale={[.34,.18,.5]} color="#fff7e7"/></group>
  </group>;
}

function Books({position=[0,0,0],count=8,scale=1}:{position?:Vec3;count?:number;scale?:number}){const colors=[p.bookRed,p.bookBlue,p.bookGreen,p.bookYellow,'#7a4e85','#d97a3d'];return <group position={position} scale={scale}>{Array.from({length:count},(_,i)=><Box key={i} position={[(i-(count-1)/2)*.16,0,0]} scale={[.13,.44+(i%3)*.06,.24]} color={colors[i%colors.length]} radius={.018} rotation={[0,0,(i%5===0?.08:0)]}/>)}</group>}
function Bookcase({position=[0,0,0],rotation=0}:{position?:Vec3;rotation?:number}){return <group position={position} rotation={[0,rotation,0]}><Box position={[0,1.55,0]} scale={[2.35,3.1,.45]} color={p.darkWood}/><Box position={[0,1.58,.25]} scale={[2.05,2.72,.12]} color="#7e452c"/>{[-.72,.15,1.02].map((y,j)=><group key={y}><Box position={[0,y+.75,.39]} scale={[2.15,.12,.54]} color={p.orangeWood}/><Books position={[0,y+.98,.52]} count={10-j}/></group>)}<Box position={[-1.08,1.55,.38]} scale={[.13,2.9,.52]} color={p.orangeWood}/><Box position={[1.08,1.55,.38]} scale={[.13,2.9,.52]} color={p.orangeWood}/></group>}
function Chair({position=[0,0,0],rotation=0,color='#d77846'}:{position?:Vec3;rotation?:number;color?:string}){return <group position={position} rotation={[0,rotation,0]}><Box position={[0,.47,0]} scale={[.85,.19,.82]} color={color}/><Box position={[0,.95,-.34]} scale={[.86,1.05,.18]} color={color}/>{[-.34,.34].flatMap(x=>[-.31,.31].map(z=><Cyl key={`${x}${z}`} position={[x,.21,z]} scale={[.12,.48,.12]} color={p.darkWood}/>))}</group>}
function Table({position=[0,0,0],rotation=0,wide=false}:{position?:Vec3;rotation?:number;wide?:boolean}){return <group position={position} rotation={[0,rotation,0]}><Box position={[0,.9,0]} scale={[wide?2.8:1.8,.18,1.05]} color={p.warmWood}/>{[-.7,.7].flatMap(x=>[-.36,.36].map(z=><Cyl key={`${x}${z}`} position={[x*(wide?1.65:1),.43,z]} scale={[.14,.86,.14]} color={p.darkWood}/>))}<Box position={[.25,1.03,0]} scale={[.68,.07,.45]} color="#4b5260"/><Box position={[.25,1.33,-.2]} scale={[.68,.52,.06]} color="#314256" rotation={[-.25,0,0]}/><Cyl position={[-.55,1.08,.15]} scale={[.3,.2,.3]} color={p.warmCream}/></group>}
function Plant({position=[0,0,0],scale=1}:{position?:Vec3;scale?:number}){return <group position={position} scale={scale}><Cyl position={[0,.25,0]} scale={[.55,.5,.55]} color="#d9773f"/>{[-.35,-.15,.1,.3].map((x,i)=><mesh key={i} position={[x*.7,.8+Math.abs(x),0]} rotation={[0,0,x]} scale={[.28,.8,.18]}><sphereGeometry args={[.5,10,8]}/><meshToonMaterial color={i%2?p.leafGreen:p.deepLeafGreen}/></mesh>)}</group>}
function Lamp({position=[0,0,0]}:{position?:Vec3}){return <group position={position}><Cyl position={[0,.75,0]} scale={[.08,1.5,.08]} color={p.darkWood}/><Cyl position={[0,1.48,0]} scale={[.65,.58,.65]} color={p.flowerYellow}/><pointLight position={[0,1.35,0]} intensity={.45} color="#ffb958" distance={4}/></group>}

function Fireplace(){return <group position={[0,0,-4.35]}><Box position={[0,1.25,0]} scale={[3,2.5,.7]} color={p.brickOrange}/><Box position={[0,.65,.4]} scale={[1.4,1.25,.3]} color="#3a2927"/><Box position={[0,2.62,.05]} scale={[3.5,.28,1]} color={p.darkWood}/><Float speed={5} floatIntensity={.12}><mesh position={[0,.65,.67]} scale={[.6,.9,.15]}><coneGeometry args={[.5,1.3,7]}/><meshBasicMaterial color="#ffb127"/></mesh><mesh position={[0,.52,.72]} scale={[.34,.55,.12]}><coneGeometry args={[.5,1.2,7]}/><meshBasicMaterial color="#fff16d"/></mesh></Float><pointLight position={[0,1.2,1.5]} intensity={2.1} color="#ff8c3c" distance={7}/><Books position={[0,2.92,.15]} count={5} scale={.75}/></group>}
function ArchedWindow({x}:{x:number}){return <group position={[x,2.4,-4.72]}><Box scale={[2,3.1,.18]} color={p.darkWood}/><mesh position={[0,0,.13]}><planeGeometry args={[1.7,2.75]}/><meshToonMaterial color="#79d0de"/></mesh><Box position={[0,0,.22]} scale={[.09,2.7,.08]} color={p.darkWood}/><Box position={[0,.1,.22]} scale={[1.7,.08,.08]} color={p.darkWood}/></group>}

function Library(){return <group><Box position={[0,-.16,0]} scale={[14,.3,11]} color="#9b522f" radius={.18}/>{Array.from({length:11},(_,i)=><Box key={i} position={[-6.4+i*1.28,.01,0]} scale={[.06,.03,10.6]} color={i%2?'#c36d3d':'#ae5c35'} radius={.01}/>)}<Box position={[0,2.3,-5.2]} scale={[14,4.6,.4]} color="#f1c784"/><Box position={[-7,2.3,0]} scale={[.4,4.6,10.8]} color="#e4a75e"/>
    <ArchedWindow x={-4.4}/><ArchedWindow x={4.4}/><Fireplace/><Bookcase position={[-5.55,0,-2.8]} rotation={Math.PI/2}/><Bookcase position={[-5.55,0,0]} rotation={Math.PI/2}/><Bookcase position={[5.55,0,-2.8]} rotation={-Math.PI/2}/>
    <Box position={[-1.8,.025,1]} scale={[5.3,.04,3.2]} color="#e7c873" radius={.2}/><Box position={[-1.8,.05,1]} scale={[4.7,.04,2.7]} color="#547e80" radius={.2}/>
    <Chair position={[-3.05,0,.2]} rotation={Math.PI/2}/><Chair position={[-1.2,0,.2]} rotation={-Math.PI/2} color="#54888b"/><Table position={[2.2,0,1.15]} wide/><Chair position={[2.2,0,1.95]}/><Chair position={[3.25,0,.35]} rotation={Math.PI} color="#6a899d"/>
    <Box position={[-1.8,.6,1.1]} scale={[1.6,.35,.9]} color={p.orangeWood}/><Books position={[-1.8,.83,1.1]} count={4} scale={.7}/><Plant position={[-4.5,0,3.3]} scale={1.25}/><Plant position={[5.1,0,-.8]} scale={.9}/><Lamp position={[4.8,0,3]}/><Cyl position={[-.3,1.2,-4.2]} scale={[.85,.85,.85]} color="#d8a642"/><Cyl position={[-.3,.57,-4.2]} scale={[.08,.65,.08]} color={p.darkWood}/>
    <Character variant={1} position={[-1.2,.52,.2]} rotation={-Math.PI/2} seated activity="reading" scale={.92}/><Character variant={2} position={[3.25,.54,.35]} rotation={Math.PI} seated activity="typing" scale={.92}/><WalkingNpc variant={0} start={[-4,0,3]} end={[1,0,3]}/>
  </group>}

function Tree({position=[0,0,0],scale=1}:{position?:Vec3;scale?:number}){return <group position={position} scale={scale}><Cyl position={[0,1,0]} scale={[.55,2,.55]} color="#7d472c"/>{[[0,2.4,0],[-.65,2.1,.1],[.65,2.15,0],[0,2,.55],[0,2.05,-.5]].map((v,i)=><mesh key={i} position={v as Vec3} scale={[1.2,1,1.15]} castShadow><sphereGeometry args={[.72,12,9]}/><meshToonMaterial color={i%2?p.leafGreen:p.deepLeafGreen}/></mesh>)}</group>}
function Flower({position,color}:{position:Vec3;color:string}){return <group position={position}><Cyl position={[0,.22,0]} scale={[.04,.45,.04]} color={p.deepLeafGreen}/>{[0,1,2,3,4].map(i=><mesh key={i} position={[Math.cos(i*1.256)*.12,.49,Math.sin(i*1.256)*.12]} scale={[.18,.08,.18]}><sphereGeometry args={[.5,8,6]}/><meshToonMaterial color={color}/></mesh>)}<mesh position={[0,.49,0]} scale={.11}><sphereGeometry args={[.5,8,6]}/><meshToonMaterial color={p.flowerYellow}/></mesh></group>}
function Garden(){const flowers=useMemo(()=>Array.from({length:48},(_,i)=>({position:[-6.2+(i%12)*1.1,0,-4.5+Math.floor(i/12)*3] as Vec3,color:[p.flowerYellow,p.flowerPink,p.flowerPurple,p.flowerRed,'#fff8dd'][i%5]})),[]);return <group><Box position={[0,-.18,0]} scale={[14,.35,11]} color={p.grassGreen} radius={.25}/><mesh position={[0,.01,.5]} rotation={[-Math.PI/2,0,.18]}><planeGeometry args={[2.2,10]}/><meshToonMaterial color="#e6c985"/></mesh><Tree position={[-5,0,-2.6]} scale={1.35}/><Tree position={[5,0,-3]} scale={1.15}/><Tree position={[5.8,0,3.5]} scale={.8}/>
  {flowers.map((f,i)=><Flower key={i} {...f}/>)}{[-5.8,-3.9,-2,3.9,5.8].map((x,i)=><mesh key={x} position={[x,.35,i%2?4.5:-4.2]} scale={[.8,.65,.8]}><sphereGeometry args={[.6,10,8]}/><meshToonMaterial color={i%2?p.deepLeafGreen:p.leafGreen}/></mesh>)}
  <Table position={[2,0,-.72]}/><Chair position={[2,0,.1]}/><Chair position={[3.1,0,-.7]} rotation={Math.PI/2} color="#55a1a2"/><Box position={[-3,.03,1.6]} scale={[2.6,.07,2]} color="#e66f62" radius={.12}/><Box position={[-3,.08,1.6]} scale={[2.35,.03,1.75]} color="#f3c858" radius={.12}/><Chair position={[-1.2,0,-2.2]} rotation={Math.PI/3} color="#e4a244"/><Plant position={[.2,0,-3.2]} scale={.7}/>
  <Character variant={0} position={[3.1,.53,-.7]} rotation={Math.PI/2} seated activity="reading" scale={.92}/><Character variant={2} position={[-3,.11,1.6]} rotation={Math.PI} seated activity="reading" scale={.9}/><WalkingNpc variant={1} start={[-4.5,0,3.4]} end={[3.5,0,3.4]}/><Sparkles count={22} scale={[12,4,9]} position={[0,2,0]} size={2} speed={.2} color="#fff5a5"/>
  </group>}

function MovingScenery(){const group=useRef<THREE.Group>(null);useFrame((_,d)=>{if(group.current){group.current.position.x-=d*1.8;if(group.current.position.x<-12)group.current.position.x=12}});return <group ref={group} position={[5,0,-4.7]}>{[-10,-6,-2,2,6,10].map((x,i)=><group key={x} position={[x,0,0]}><mesh position={[0,2,-2]} scale={[3+i%2,2.5,1]}><coneGeometry args={[1,1,5]}/><meshToonMaterial color={i%2?'#69977c':'#53788b'}/></mesh><Cyl position={[i%2?.8:-.8,.65,0]} scale={[.18,1.3,.18]} color="#59422c"/><mesh position={[i%2?.8:-.8,1.5,0]} scale={[.8,1.5,.8]}><coneGeometry args={[.5,1,7]}/><meshToonMaterial color={p.deepLeafGreen}/></mesh></group>)}</group>}
function Train(){return <group><Box position={[0,-.2,.5]} scale={[13,.35,7]} color="#8b5b46"/><Box position={[0,3,-3]} scale={[13,6,.35]} color="#f3d28e"/><Box position={[0,3,4]} scale={[13,6,.35]} color="#d96843"/><Box position={[-6.5,2,.5]} scale={[.35,4,7]} color={p.navy}/><Box position={[6.5,2,.5]} scale={[.35,4,7]} color={p.navy}/>
  <MovingScenery/>{[-4.5,-1.5,1.5,4.5].map(x=><group key={x} position={[x,2.3,-2.78]}><Box scale={[2.35,2.15,.2]} color={p.navy}/><mesh position={[0,0,.14]}><planeGeometry args={[2,1.8]}/><meshToonMaterial color="#75cce8" transparent opacity={.72}/></mesh></group>)}
  {[-4.3,-2.5,2.2,4].map((x,i)=><group key={x}><Chair position={[x,0,.15]} color={i%2?'#d65e43':'#3c7c85'}/><Box position={[x,.9,-.5]} scale={[1.3,.14,.8]} color={p.warmWood}/><Chair position={[x,0,-1.15]} rotation={Math.PI} color={i%2?'#3c7c85':'#d65e43'}/></group>)}
  <Box position={[0,3.1,.5]} scale={[12,.15,6]} color="#f6e7bc"/><Box position={[0,2.7,-2.35]} scale={[12,.18,.55]} color={p.orangeWood}/>{[-4,-2,0,2,4].map(x=><Cyl key={x} position={[x,2.75,-2.1]} scale={[.5,.35,.45]} color={x%4?p.bookBlue:p.bookRed}/>)}
  {[-4.2,0,4.2].map(x=><Lamp key={x} position={[x,1.5,3.55]}/>)}<Character variant={2} position={[4,.53,.15]} seated rotation={Math.PI} activity="reading" scale={.9}/><Character variant={1} position={[-4.3,.53,-1.15]} seated activity="typing" scale={.9}/><WalkingNpc variant={0} start={[-5,0,2.7]} end={[5,0,2.7]}/>
  </group>}

function WalkingNpc({variant,start,end}:{variant:number;start:Vec3;end:Vec3}){const ref=useRef<THREE.Group>(null);const [moving]=useState(true);useFrame(({clock})=>{if(!ref.current)return;const u=(Math.sin(clock.elapsedTime*.35)+1)/2;const dir=Math.cos(clock.elapsedTime*.35)>=0?1:-1;ref.current.position.set(THREE.MathUtils.lerp(start[0],end[0],u),start[1],THREE.MathUtils.lerp(start[2],end[2],u));ref.current.rotation.y=yawForMovement((end[0]-start[0])*dir,(end[2]-start[2])*dir)});return <group ref={ref}><Character variant={variant} moving={moving} scale={.88}/></group>}

function CameraRig({definition,focus}:{definition:SceneDefinition;focus:boolean}){const {camera}=useThree();const shotStart=useRef(0),wasFocus=useRef(false);useFrame(({clock})=>{if(focus&&!wasFocus.current){shotStart.current=clock.elapsedTime;wasFocus.current=true}if(!focus)wasFocus.current=false;let pos=definition.explorationCamera.position,target=definition.explorationCamera.target;if(focus){const elapsed=clock.elapsedTime-shotStart.current;let accum=0;let shot=definition.cinematicShots[0];for(const s of definition.cinematicShots){if(elapsed%(definition.cinematicShots.reduce((a,b)=>a+b.duration,0))>=accum)shot=s;accum+=s.duration}pos=shot.position;target=shot.target;if(shot.endPosition){const k=(elapsed%shot.duration)/shot.duration;pos=[THREE.MathUtils.lerp(pos[0],shot.endPosition[0],k),THREE.MathUtils.lerp(pos[1],shot.endPosition[1],k),THREE.MathUtils.lerp(pos[2],shot.endPosition[2],k)]}}camera.position.lerp(new THREE.Vector3(...pos),.025);const q=new THREE.Quaternion();const m=new THREE.Matrix4().lookAt(camera.position,new THREE.Vector3(...target),camera.up);q.setFromRotationMatrix(m);camera.quaternion.slerp(q,.035)});return null}
function Boundaries({d}:{d:SceneDefinition}){void d;return <><RigidBody type="fixed"><CuboidCollider args={[7,.2,5.5]} position={[0,-.25,0]}/><CuboidCollider args={[7,2,.2]} position={[0,1.5,-5.3]}/><CuboidCollider args={[.2,2,5.5]} position={[-7,1.5,0]}/><CuboidCollider args={[.2,2,5.5]} position={[7,1.5,0]}/></RigidBody></>}
function Player({definition,onNear}:{definition:SceneDefinition;onNear:(s:StudySpot|null)=>void}){const body=useRef<RapierRigidBody>(null);const keys=useRef(new Set<string>());const character=useGameStore(s=>s.character),focusEnd=useGameStore(s=>s.focusEnd),activeSpot=useGameStore(s=>s.activeSpot);const [moving,setMoving]=useState(false),[waving,setWaving]=useState(false);const yaw=useRef(0);const spot=activeSpot?definition.studySpots.find(s=>s.id===activeSpot):null;
  useEffect(()=>{let waveTimer:ReturnType<typeof setTimeout>;const down=(e:KeyboardEvent)=>{keys.current.add(e.key.toLowerCase());if(e.key.toLowerCase()==='f'){setWaving(true);clearTimeout(waveTimer);waveTimer=setTimeout(()=>setWaving(false),1200)}},up=(e:KeyboardEvent)=>keys.current.delete(e.key.toLowerCase());addEventListener('keydown',down);addEventListener('keyup',up);return()=>{clearTimeout(waveTimer);removeEventListener('keydown',down);removeEventListener('keyup',up)}},[]);
  useFrame((_,dt)=>{if(!body.current||focusEnd)return;const t=body.current.translation();let x=(keys.current.has('d')?1:0)-(keys.current.has('a')?1:0),z=(keys.current.has('s')?1:0)-(keys.current.has('w')?1:0);const len=Math.hypot(x,z);if(len){x/=len;z/=len;const target=yawForMovement(x,z);yaw.current+=Math.atan2(Math.sin(target-yaw.current),Math.cos(target-yaw.current))*.15;body.current.setNextKinematicRotation(new THREE.Quaternion().setFromEuler(new THREE.Euler(0,yaw.current,0)));body.current.setNextKinematicTranslation({x:THREE.MathUtils.clamp(t.x+x*dt*2.8,...definition.bounds.x),y:0,z:THREE.MathUtils.clamp(t.z+z*dt*2.8,...definition.bounds.z)});setMoving(true)}else setMoving(false);let nearest:StudySpot|null=null,dist=1.65;for(const s of definition.studySpots){const d=distanceXZ([t.x,0,t.z],s.standingPosition);if(d<dist){nearest=s;dist=d}}onNear(nearest)});
  if(spot)return <Character variant={character} position={spot.sittingPosition} rotation={spot.sittingRotation} seated activity={spot.animation}/>;
  return <RigidBody ref={body} type="kinematicPosition" colliders={false} position={definition.playerSpawn} enabledRotations={[false,false,false]}><CuboidCollider args={[.32,.7,.32]} position={[0,.72,0]}/><Character variant={character} moving={moving} activity={waving?'wave':'idle'}/></RigidBody>}

function World({definition,onNear}:{definition:SceneDefinition;onNear:(s:StudySpot|null)=>void}){const focus=!!useGameStore(s=>s.focusEnd);const dev=new URLSearchParams(typeof location!=='undefined'?location.search:'').get('dev')==='1';return <Canvas shadows dpr={[1,1.5]} camera={{position:definition.explorationCamera.position,fov:42,near:.1,far:80}} gl={{antialias:true,toneMapping:THREE.ACESFilmicToneMapping}}><color attach="background" args={[definition.id==='library'?'#6b3e32':definition.id==='garden'?'#8dd9ed':'#568eb1']}/><fog attach="fog" args={[definition.id==='train'?'#8ccfe1':'#e8c990',18,42]}/><ambientLight intensity={1.65}/><hemisphereLight args={['#bceaff','#7a5436',1.5]}/><directionalLight castShadow position={[7,12,9]} intensity={2.8} color="#fff1c5" shadow-mapSize={[1024,1024]}/><Suspense fallback={null}><Physics gravity={[0,-18,0]} debug={dev}><Boundaries d={definition}/>{definition.id==='library'?<Library/>:definition.id==='garden'?<Garden/>:<Train/>}<Player definition={definition} onNear={onNear}/></Physics><Environment preset="sunset"/><ContactShadows position={[0,.02,0]} opacity={.42} scale={20} blur={2.5} far={4}/>{dev&&definition.studySpots.map(s=><group key={s.id}><mesh position={s.standingPosition}><sphereGeometry args={[.12]}/><meshBasicMaterial color="lime"/></mesh><mesh position={s.sittingPosition}><sphereGeometry args={[.12]}/><meshBasicMaterial color="blue"/></mesh><mesh position={s.cameraTarget}><sphereGeometry args={[.12]}/><meshBasicMaterial color="yellow"/></mesh></group>)}</Suspense><CameraRig definition={definition} focus={focus}/></Canvas>}

function Menu(){const character=useGameStore(s=>s.character),setCharacter=useGameStore(s=>s.setCharacter),enter=useGameStore(s=>s.enterScene),progress=useGameStore(s=>s.progress);const cards:[SceneId,string,string,string][]=[['library','The Lantern Library','Warm & quiet','⌂'],['garden','Sunpetal Garden','Fresh & peaceful','✿'],['train','The Daydream Line','Study on the move','◇']];return <main className="menu-shell"><div className="cloud cloud-a"/><div className="cloud cloud-b"/><header className="brand"><span className="brand-mark">ST</span><b>StudyTown</b><span className="tiny-pill">A cozy focus game</span><span className="progress-pill">✦ {progress.focusPoints} focus</span></header><section className="menu-copy"><p className="eyebrow">YOUR LITTLE PLACE TO FOCUS</p><h1>Where shall we<br/><em>study today?</em></h1><p className="intro">Pick a cozy corner, settle in, and let the world drift by while you focus.</p></section><section className="character-pick"><span className="pick-label">Study buddy</span><div className="character-row">{[0,1,2].map(i=><button key={i} onClick={()=>setCharacter(i)} className={`avatar avatar-${i} ${character===i?'selected':''}`} aria-label={`Character ${i+1}`}><span className="hair"/><span className="face"><i/><i/></span><span className="body"/></button>)}</div></section><section className="place-grid">{cards.map(([id,name,note,icon],i)=><button className={`place-card ${id}`} key={id} onClick={()=>enter(id)}><span className="card-number">0{i+1}</span><span className="scene-art"><b>{icon}</b><i/><i/><i/></span><span className="card-copy"><strong>{name}</strong><small>{note}</small></span><span className="enter">Enter <b>→</b></span></button>)}</section><footer><span>WASD to stroll</span><span>•</span><span>E to settle in</span><span>•</span><span>F to wave</span></footer></main>}
function Loading({definition}:{definition:SceneDefinition}){const finish=useGameStore(s=>s.finishLoading);useEffect(()=>{const t=setTimeout(finish,1500);return()=>clearTimeout(t)},[finish]);return <div className={`loading ${definition.id}`}><div className="loading-icon">{definition.id==='library'?'⌂':definition.id==='garden'?'✿':'◇'}</div><h2>{definition.loading}</h2><div className="loading-line"><i/></div></div>}
function Setup({spot,onClose}:{spot:StudySpot;onClose:()=>void}){const start=useGameStore(s=>s.startFocus),[custom,setCustom]=useState(25);const dev=new URLSearchParams(location.search).get('dev')==='1';return <div className="modal-back"><div className="focus-card"><button className="modal-close" onClick={onClose}>×</button><p className="eyebrow">{spot.label}</p><h2>Start a focus session</h2><p>How long would you like to settle in?</p><div className="duration-row">{[25,50,90].map(m=><button key={m} onClick={()=>start(spot.id,m)}><b>{m}</b><small>min</small></button>)}</div><label className="custom-time">Custom <input type="number" min="1" max="180" value={custom} onChange={e=>setCustom(clampDuration(Number(e.target.value)))}/><button onClick={()=>start(spot.id,custom)}>Start</button></label>{dev&&<button className="dev-session" onClick={()=>start(spot.id,1/6)}>10-second developer session</button>}</div></div>}
function FocusHud({definition}:{definition:SceneDefinition}){const end=useGameStore(s=>s.focusEnd),endFocus=useGameStore(s=>s.endFocus);const [left,setLeft]=useState(()=>end?remainingMs(end):0);useEffect(()=>{const timer=setInterval(()=>{if(!end)return;const ms=remainingMs(end);setLeft(ms);if(ms<=0){clearInterval(timer);endFocus(true)}},250);return()=>clearInterval(timer)},[end,endFocus]);return end?<div className="focus-hud"><p>{definition.name}</p><b>{formatTime(left)}</b><span>Focus</span><button onClick={()=>endFocus(false)}>End session</button></div>:null}
function Completion(){const completion=useGameStore(s=>s.completion),minutes=useGameStore(s=>s.focusMinutes),clear=useGameStore(s=>s.clearCompletion),menu=useGameStore(s=>s.menu),scene=useGameStore(s=>s.scene),enter=useGameStore(s=>s.enterScene);if(!completion)return null;return <div className="modal-back"><div className="focus-card complete"><span className="celebrate">✦</span><p className="eyebrow">SESSION COMPLETE</p><h2>Nice work.</h2><p><b>{Math.round(minutes)} minutes</b> focused · +{Math.round(minutes)} Focus</p><div className="completion-actions"><button onClick={()=>{clear();if(scene)enter(scene)}}>Study again</button><button onClick={clear}>Explore</button><button onClick={menu}>Choose another place</button></div></div></div>}
function DevPanel(){const reset=useGameStore(s=>s.reset),menu=useGameStore(s=>s.menu);if(typeof location==='undefined'||new URLSearchParams(location.search).get('dev')!=='1')return null;return <div className="dev-panel"><b>DEV</b><button onClick={menu}>Scenes</button><button onClick={reset}>Reset save</button></div>}
function Game({definition}:{definition:SceneDefinition}){const [near,setNear]=useState<StudySpot|null>(null),[setup,setSetup]=useState<StudySpot|null>(null);const focus=useGameStore(s=>!!s.focusEnd),menu=useGameStore(s=>s.menu);useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key.toLowerCase()==='e'&&near&&!focus)setSetup(near);if(e.key==='Escape')menu()};addEventListener('keydown',key);return()=>removeEventListener('keydown',key)},[near,focus,menu]);return <main className="game-shell"><World definition={definition} onNear={setNear}/>{!focus&&<div className="game-top"><button onClick={menu}>← Places</button><div><b>{definition.name}</b><span>{definition.subtitle}</span></div><span className="controls">WASD stroll · E study · F wave</span></div>}{near&&!focus&&!setup&&<button className="interact" onClick={()=>setSetup(near)}><kbd>E</kbd><span>{near.label}</span></button>}{setup&&!focus&&<Setup spot={setup} onClose={()=>setSetup(null)}/>}<FocusHud definition={definition}/><Completion/><DevPanel/></main>}

export default function StudyTown(){const screen=useGameStore(s=>s.screen),scene=useGameStore(s=>s.scene);if(screen==='menu'||!scene)return <Menu/>;const definition=scenes[scene];if(screen==='loading')return <Loading definition={definition}/>;return <Game definition={definition}/>}
